[project]
name = "agentic-marketplace-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.66.0",
    "google-genai>=1.34.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.13.1",
]
